### ISSUE TITLE
Eddystone UID frames not seen

### ISSUE THREAD

**Issue by eltoro81** [citruz/beacontools#10]
Please make RFU fields of Eddystone UID frame optional or print a warning when a UID frame is received missing RFU field. Today it is just discarded and took me some time to figure out why.

On top of that it also seems like temperature is not reported correct. It seems it cannot parse the fixed-point artithmetic of the frame. xx.xx. Maybe the beacons tested just reported even degrees, hence it was reported little endian? My beacon reports with decimal value...like 23.21

I´m testing with Bluvision Beeks Beacons
Thank you

**Comment by citruz** [comment]
Fixed with 1.3.0
