### ISSUE TITLE
Choose the BT device

### ISSUE THREAD

**Issue by c1p81** [citruz/beacontools#13]
Hi, i have 2 BT devices (one integrated in a old MacBook Pro not BLE and one USB dongle supporting BLE).
I need to choose the USB Dongle to listen Estimote Beacons...how i can set the scanner example to use hci1 and not hc0???
thanks Luca

**Comment by citruz** [comment]
Use the `bt_device_id` parameter to the BeaconScanner class:
```
scanner = BeaconScanner(callback, /* ... */, bt_device_id=1)
```
