### ISSUE TITLE
[Bug] device_filters.py custom Filter initialization is broken, rejects 0x0 as a valid Property for iBeacon Major/Minor and possibly others

### ISSUE THREAD

**Issue by cereal** [citruz/beacontools#30]
First a big thank you for this lib :+1: 

I'm writing an application, that has to match on an exact pair of Major and Minor ID and only call the callback if all of my filters do match.
I use the IBeaconFilter like this:
`fltr = IBeaconFilter(major=0xff00, minor=0x0000)`, but then I receive all iBeacon advertisements for
beacons with the Major ID 0xff00 (minor is "ignored", `0x0 == False`).. When I try to use the following filter it works as expected (I only see packets of that exact iBeacon) `fltr = IBeaconFilter(major=0xff00, minor=0x0001)`

So the bug is in the device_filters.py IBeaconFilter initialization, because `0x0 == False`, so the following line is False

https://github.com/citruz/beacontools/blob/master/beacontools/device_filters.py#L36

so I'd refactor the code like this:  
  
```python
    class IBeaconFilter(DeviceFilter):
        """Filter for iBeacon."""

        def __init__(self, uuid=None, major=None, minor=None):
            """Initialize filter."""
            super(IBeaconFilter, self).__init__()
            if uuid is None and major is None and minor is None:
                raise ValueError("IBeaconFilter needs at least one argument set")
            if uuid is not None:
                self.properties['uuid'] = uuid
            if major is not None:
                self.properties['major'] = major
            if minor is not None:
                self.properties['minor'] = minor
```
This is kind of ugly, but should work correctly :)

**Comment by cereal** [comment]
Oh I think I found the real issue of my Problem, the filter initialization is broken, because `0x0 == False`, so the following line is False
https://github.com/citruz/beacontools/blob/master/beacontools/device_filters.py#L36

so I'd rewrite the code like this:
`python
class IBeaconFilter(DeviceFilter):
    """Filter for iBeacon."""

    def __init__(self, uuid=None, major=None, minor=None):
        """Initialize filter."""
        super(IBeaconFilter, self).__init__()
        if not uuid and not major and not minor:
            raise ValueError("IBeaconFilter needs at least one argument set")
        if uuid is not None:
            self.properties['uuid'] = uuid
        if major is not None:
            self.properties['major'] = major
        if minor is not None:
            self.properties['minor'] = minor
`
This is kind of ugly, but should work correctly :)

**Comment by citruz** [comment]
Good catch! Thanks for reporting and providing a solution.
