### ISSUE TITLE
Get the BLE beacon name

### ISSUE THREAD

**Issue by carlos-sarmiento** [citruz/beacontools#38]
I'm trying to understand if it is possible using this library to get (besides the information already there) the name of the bluetooth beacon. 

I checked the code and didn't see any place where the information might be loaded. But I rather ask and be sure.

**Comment by citruz** [comment]
The name is not part of the standard beacon format. Usually it is fetched online from the backend of the beacon manufacturer (if you use their apps). So, no unfortunately this is not possible.
