### ISSUE TITLE
Problems with pip install beacontools[scan] with Debian 8

### ISSUE THREAD

**Issue by jvw1954** [citruz/beacontools#4]
jaap@custard:~$ sudo apt-get install libbluetooth-dev libcap2-bin\
> 
[sudo] password for jaap: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libbluetooth-dev is already the newest version.
libcap2-bin is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jaap@custard:~$ sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which python))
jaap@custard:~$ pip install beacontools[scan]
Downloading/unpacking beacontools[scan]
  Downloading beacontools-1.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): construct==2.8.12 in /usr/local/lib/python2.7/dist-packages (from beacontools[scan])
Downloading/unpacking PyBluez==0.22 (from beacontools[scan])
  Downloading PyBluez-0.22.zip (109kB): 109kB downloaded
  Running setup.py (path:/tmp/pip-build-c3w9ob/PyBluez/setup.py) egg_info for package PyBluez
    
    warning: no files found matching '*.h' under directory 'osx'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*.o' found under directory '*'
    warning: no previously-included files matching '*.opp' found under directory '*'
Installing collected packages: beacontools, PyBluez
  Running setup.py install for PyBluez
    building 'bluetooth._bluetooth' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./port3 -I/usr/include/python2.7 -c bluez/btmodule.c -o build/temp.linux-x86_64-2.7/bluez/btmodule.o
    In file included from bluez/btmodule.c:20:0:
    bluez/btmodule.h:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-c3w9ob/PyBluez/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oKbi5u-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/btcommon.py -> build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/msbt.py -> build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/widcomm.py -> build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/__init__.py -> build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/ble.py -> build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/osx.py -> build/lib.linux-x86_64-2.7/bluetooth

copying bluetooth/bluez.py -> build/lib.linux-x86_64-2.7/bluetooth

running build_ext

building 'bluetooth._bluetooth' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/bluez

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./port3 -I/usr/include/python2.7 -c bluez/btmodule.c -o build/temp.linux-x86_64-2.7/bluez/btmodule.o

In file included from bluez/btmodule.c:20:0:

bluez/btmodule.h:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-c3w9ob/PyBluez/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oKbi5u-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-c3w9ob/PyBluez
Storing debug log for failure in /home/jaap/.pip/pip.log
jaap@custard:~$

**Comment by citruz** [comment]
Looks like you need to install the headers for python:
```
sudo apt-get install python-dev
```
