### ISSUE TITLE
Custom Format for TLM Frames

### ISSUE THREAD

**Issue by tan0300** [citruz/beacontools#49]
Hi, we are about to develop a device wherein we will be using the eddystone beacon as our protocol. And it seems to be that the format of the packets are standard to any existing app. But what we did was we customized the format of the packets to add more sensor data (heart rate and spo2)

Now the problem was, when I used this library as sentry, I can't seem to find any filter packet filter that will enable me to display the tlm frames as raw packets.

Will it be possible to display the tlm frames as raw packets using this library?

Thank you,
Jonathan

**Comment by citruz** [comment]
No this is not possible. You would need to create your own fork and modify the eddystone struct definitions accordingly.
