### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by rupak78** [citruz/beacontools#59]
Hello,

I am trying to parse the BLE Gateway data send to cloud. The data is getting send in text format,which I am unable to parse using parse_packet() function.

Data send is '0201061AFF4C000215E2C56DB5DFFB48D2B060D0F5A71096E027100000D7' .

Any help is very much appreciated.

Thanks And Regards,
Rupak Banerjee.

**Comment by citruz** [comment]
You can use python‘s `binascii.unhexlify` to convert a hex string into bytes:
https://docs.python.org/3.6/library/binascii.html

**Comment by rupak78** [comment]
Many Many Thanks. It works fine.
