### ISSUE TITLE
simple question about BeaconScanner.start

### ISSUE THREAD

**Issue by gokhalen** [citruz/beacontools#68]
I've been going through the example 

https://github.com/citruz/beacontools/blob/master/examples/scanner_eddystone_example.py

My question is does scanner.start() on line 24 start a scanning process in the background, which continues running and calling the callback, while the main code waits for 10 seconds due to ```time.sleep(10)``` ?

Thanks,

Nachiket

**Comment by citruz** [comment]
Yes, that is exactly how it works.
